using CastleAssault.Art;
using CastleAssault.Core;
using TMPro;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.InputSystem.UI;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

namespace CastleAssault.UI
{
    /// <summary>
    /// Menú principal: título, JUGAR, CRÉDITOS y selector de idioma (EN/ES).
    /// Construye toda la interfaz por código y crea el EventSystem si no existe.
    /// </summary>
    public class MainMenuController : MonoBehaviour
    {
        [Header("Configuración")]
        [SerializeField] private string _gameSceneName = "SampleScene";

        [Header("Créditos (uno por idioma)")]
        [TextArea(4, 10)]
        [SerializeField]
        private string _creditsTextEnglish =
            "Programming & art\n[Your name]\n\n" +
            "Music & sound effects\nGenerated by code\n\n" +
            "Made for the Game Jam\nThanks for playing!";

        [TextArea(4, 10)]
        [SerializeField]
        private string _creditsTextSpanish =
            "Programación y arte\n[Tu nombre]\n\n" +
            "Música y efectos\nGenerados por código\n\n" +
            "Hecho para la Game Jam\n¡Gracias por jugar!";

        private static readonly Vector2 ReferenceResolution = new Vector2(1080f, 1920f);

        private GameObject _mainPanel;
        private GameObject _creditsPanel;
        private Image _knightImage;
        private RectTransform _titleRt;
        private float _bobTimer;

        // Textos que cambian con el idioma
        private TextMeshProUGUI _titleText;
        private TextMeshProUGUI _hintText;
        private TextMeshProUGUI _playLabel;
        private TextMeshProUGUI _creditsLabel;
        private TextMeshProUGUI _languageLabel;
        private TextMeshProUGUI _creditsTitleText;
        private TextMeshProUGUI _creditsBodyText;
        private TextMeshProUGUI _backLabel;

        private void Awake()
        {
            Time.timeScale = 1f; // Por si venimos de una partida pausada
        }

        private void Start()
        {
            SetupCamera();
            EnsureEventSystem();
            BuildMenu();
            RefreshTexts();
        }

        private void Update()
        {
            // Pequeña animación: el caballero y el título "respiran"
            _bobTimer += Time.deltaTime;

            if (_knightImage != null)
            {
                float s = 1f + Mathf.Sin(_bobTimer * 2f) * 0.04f;
                _knightImage.rectTransform.localScale = new Vector3(s, s, 1f);
            }

            if (_titleRt != null)
            {
                float y = Mathf.Sin(_bobTimer * 1.5f) * 8f;
                _titleRt.anchoredPosition = new Vector2(0f, y);
            }
        }

        #region Setup
        private void SetupCamera()
        {
            Camera cam = Camera.main;
            if (cam == null) return;
            cam.clearFlags = CameraClearFlags.SolidColor;
            cam.backgroundColor = new Color(0.08f, 0.06f, 0.10f);
        }

        private void EnsureEventSystem()
        {
            if (FindAnyObjectByType<EventSystem>() != null) return;

            GameObject es = new GameObject("EventSystem");
            es.AddComponent<EventSystem>();
            es.AddComponent<InputSystemUIInputModule>();
        }
        #endregion

        #region Build UI
        private void BuildMenu()
        {
            GameObject canvasGo = new GameObject("MenuCanvas");
            Canvas canvas = canvasGo.AddComponent<Canvas>();
            canvas.renderMode = RenderMode.ScreenSpaceOverlay;
            CanvasScaler scaler = canvasGo.AddComponent<CanvasScaler>();
            scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
            scaler.referenceResolution = ReferenceResolution;
            scaler.screenMatchMode = CanvasScaler.ScreenMatchMode.MatchWidthOrHeight;
            scaler.matchWidthOrHeight = 0.5f;
            canvasGo.AddComponent<GraphicRaycaster>();

            // Fondo
            Image bg = CreateImage(canvasGo.transform, "Background", new Color(0.08f, 0.06f, 0.10f));
            Stretch(bg.rectTransform);

            BuildMainPanel(canvasGo.transform);
            BuildCreditsPanel(canvasGo.transform);

            _creditsPanel.SetActive(false);
        }

        private void BuildMainPanel(Transform parent)
        {
            _mainPanel = new GameObject("MainPanel", typeof(RectTransform));
            _mainPanel.transform.SetParent(parent, false);
            Stretch(_mainPanel.GetComponent<RectTransform>());

            // Título
            _titleText = CreateLabel(_mainPanel.transform, "",
                new Vector2(0.5f, 0.82f), new Vector2(1000f, 250f), 110);
            _titleText.color = new Color(1f, 0.85f, 0.2f);
            _titleText.fontStyle = FontStyles.Bold;
            AddShadow(_titleText.gameObject);
            _titleRt = _titleText.rectTransform;

            // Caballero
            GameObject knightGo = new GameObject("Knight");
            knightGo.transform.SetParent(_mainPanel.transform, false);
            _knightImage = knightGo.AddComponent<Image>();
            _knightImage.sprite = PixelSpriteFactory.KnightSprite;
            _knightImage.preserveAspect = true;
            _knightImage.raycastTarget = false;
            RectTransform kRt = knightGo.GetComponent<RectTransform>();
            kRt.anchorMin = kRt.anchorMax = new Vector2(0.5f, 0.56f);
            kRt.sizeDelta = new Vector2(420f, 580f);

            // Botones
            Button play = CreateButton(_mainPanel.transform, "",
                new Vector2(0.5f, 0.32f), new Vector2(560f, 130f), new Color(0.15f, 0.55f, 0.18f), 52);
            play.onClick.AddListener(OnPlayClicked);
            _playLabel = play.GetComponentInChildren<TextMeshProUGUI>();

            Button credits = CreateButton(_mainPanel.transform, "",
                new Vector2(0.5f, 0.20f), new Vector2(560f, 110f), new Color(0.25f, 0.30f, 0.55f), 52);
            credits.onClick.AddListener(() => ShowCredits(true));
            _creditsLabel = credits.GetComponentInChildren<TextMeshProUGUI>();

            // Botón de idioma (arriba a la derecha)
            Button lang = CreateButton(_mainPanel.transform, "",
                new Vector2(0.80f, 0.955f), new Vector2(380f, 90f), new Color(0.45f, 0.30f, 0.10f), 40);
            lang.onClick.AddListener(OnLanguageClicked);
            _languageLabel = lang.GetComponentInChildren<TextMeshProUGUI>();

            // Pista de controles
            _hintText = CreateLabel(_mainPanel.transform, "",
                new Vector2(0.5f, 0.07f), new Vector2(1000f, 80f), 34);
            _hintText.color = new Color(0.7f, 0.7f, 0.75f);
        }

        private void BuildCreditsPanel(Transform parent)
        {
            _creditsPanel = new GameObject("CreditsPanel", typeof(RectTransform));
            _creditsPanel.transform.SetParent(parent, false);
            Stretch(_creditsPanel.GetComponent<RectTransform>());

            Image dim = CreateImage(_creditsPanel.transform, "Dim", new Color(0f, 0f, 0f, 0.85f));
            Stretch(dim.rectTransform);

            Image box = CreateImage(_creditsPanel.transform, "Box", new Color(0.12f, 0.09f, 0.14f, 1f));
            RectTransform boxRt = box.rectTransform;
            boxRt.anchorMin = new Vector2(0.06f, 0.15f);
            boxRt.anchorMax = new Vector2(0.94f, 0.88f);
            boxRt.offsetMin = boxRt.offsetMax = Vector2.zero;

            _creditsTitleText = CreateLabel(_creditsPanel.transform, "",
                new Vector2(0.5f, 0.80f), new Vector2(900f, 120f), 80);
            _creditsTitleText.color = new Color(1f, 0.85f, 0.2f);
            _creditsTitleText.fontStyle = FontStyles.Bold;
            AddShadow(_creditsTitleText.gameObject);

            _creditsBodyText = CreateLabel(_creditsPanel.transform, "",
                new Vector2(0.5f, 0.52f), new Vector2(900f, 700f), 50);
            _creditsBodyText.color = Color.white;
            _creditsBodyText.textWrappingMode = TextWrappingModes.Normal;

            Button back = CreateButton(_creditsPanel.transform, "",
                new Vector2(0.5f, 0.22f), new Vector2(480f, 110f), new Color(0.35f, 0.15f, 0.12f), 52);
            back.onClick.AddListener(() => ShowCredits(false));
            _backLabel = back.GetComponentInChildren<TextMeshProUGUI>();
        }
        #endregion

        #region Actions
        private void OnPlayClicked()
        {
            SceneManager.LoadScene(_gameSceneName);
        }

        private void OnLanguageClicked()
        {
            Loc.Toggle();
            RefreshTexts();
        }

        private void ShowCredits(bool show)
        {
            _creditsPanel.SetActive(show);
            _mainPanel.SetActive(!show);
        }

        /// <summary>Vuelve a escribir todos los textos en el idioma actual.</summary>
        private void RefreshTexts()
        {
            bool english = Loc.Current == Language.English;

            if (_titleText != null) _titleText.text = Loc.Get("title");
            if (_hintText != null) _hintText.text = Loc.Get("hint");
            if (_playLabel != null) _playLabel.text = Loc.Get("play");
            if (_creditsLabel != null) _creditsLabel.text = Loc.Get("credits");
            if (_languageLabel != null) _languageLabel.text = Loc.Get("language");
            if (_creditsTitleText != null) _creditsTitleText.text = Loc.Get("credits");
            if (_backLabel != null) _backLabel.text = Loc.Get("back");
            if (_creditsBodyText != null)
                _creditsBodyText.text = english ? _creditsTextEnglish : _creditsTextSpanish;
        }
        #endregion

        #region UI Helpers
        private Image CreateImage(Transform parent, string name, Color color)
        {
            GameObject go = new GameObject(name);
            go.transform.SetParent(parent, false);
            Image img = go.AddComponent<Image>();
            img.color = color;
            return img;
        }

        private void Stretch(RectTransform rt)
        {
            rt.anchorMin = Vector2.zero;
            rt.anchorMax = Vector2.one;
            rt.offsetMin = Vector2.zero;
            rt.offsetMax = Vector2.zero;
        }

        private TextMeshProUGUI CreateLabel(Transform parent, string text, Vector2 anchor,
            Vector2 size, int fontSize)
        {
            GameObject go = new GameObject("Label");
            go.transform.SetParent(parent, false);
            TextMeshProUGUI tmp = go.AddComponent<TextMeshProUGUI>();
            tmp.text = text;
            tmp.fontSize = fontSize;
            tmp.alignment = TextAlignmentOptions.Center;
            tmp.color = Color.white;
            tmp.raycastTarget = false;

            RectTransform rt = go.GetComponent<RectTransform>();
            rt.anchorMin = rt.anchorMax = anchor;
            rt.pivot = new Vector2(0.5f, 0.5f);
            rt.sizeDelta = size;
            rt.anchoredPosition = Vector2.zero;
            return tmp;
        }

        private Button CreateButton(Transform parent, string label, Vector2 anchor,
            Vector2 size, Color bgColor, int fontSize)
        {
            GameObject go = new GameObject("Btn_" + label);
            go.transform.SetParent(parent, false);

            Image bg = go.AddComponent<Image>();
            bg.color = bgColor;

            Button btn = go.AddComponent<Button>();
            btn.targetGraphic = bg;
            ColorBlock colors = btn.colors;
            colors.normalColor = Color.white;
            colors.highlightedColor = new Color(1.25f, 1.25f, 1.25f, 1f);
            colors.pressedColor = new Color(0.7f, 0.7f, 0.7f, 1f);
            btn.colors = colors;

            RectTransform rt = go.GetComponent<RectTransform>();
            rt.anchorMin = rt.anchorMax = anchor;
            rt.pivot = new Vector2(0.5f, 0.5f);
            rt.sizeDelta = size;
            rt.anchoredPosition = Vector2.zero;

            GameObject txtGo = new GameObject("BtnText");
            txtGo.transform.SetParent(go.transform, false);
            TextMeshProUGUI tmp = txtGo.AddComponent<TextMeshProUGUI>();
            tmp.text = label;
            tmp.fontSize = fontSize;
            tmp.color = Color.white;
            tmp.fontStyle = FontStyles.Bold;
            tmp.alignment = TextAlignmentOptions.Center;
            tmp.raycastTarget = false;
            Stretch(txtGo.GetComponent<RectTransform>());

            return btn;
        }

        private void AddShadow(GameObject go)
        {
            Shadow shadow = go.AddComponent<Shadow>();
            shadow.effectColor = new Color(0f, 0f, 0f, 0.8f);
            shadow.effectDistance = new Vector2(4f, -4f);
        }
        #endregion
    }
}